Dev zsx
shenweichen/DeepCTR-Torch pull request #163
Opened 2021-03-20 13:13 UTC by zanshuxun

2021-03-21 03:04 UTC, shenweichen commented on deepctr_torch/layers/interaction.py
> -        - **str** : String, types of bilinear functions used in this layer.
挺细心啊

2021-03-21 03:05 UTC, shenweichen commented on deepctr_torch/layers/interaction.py
> +        if self.scaling:
这个scaling是在哪里被调用到的？

2021-03-21 03:07 UTC, shenweichen commented on deepctr_torch/layers/interaction.py
> +            nn.ParameterList
这行是多余的，估计测试用例没有覆盖到这个分支，建议可以补充一下测试用例。

2021-03-21 03:08 UTC, shenweichen commented on deepctr_torch/layers/interaction.py
> +            self.kernels = nn.Parameter(torch.Tensor(self.layer_num, in_features, 1))
用nn.Parameter替换nn.ParameterList的原因是什么呀？

2021-03-21 03:09 UTC, shenweichen commented on deepctr_torch/layers/interaction.py
> +        for i in range(self.kernels.shape[0]):
初始化操作单独放在后面而不是像以前一样放在nn.Parameter里的原因？

2021-03-21 03:20 UTC, shenweichen commented on deepctr_torch/models/din.py
> +                "dcn, dcnmix and din are not supported with multi gpus now!")
为什么这三个模型目前无法支持？

2021-03-21 03:22 UTC, shenweichen commented on deepctr_torch/models/ifm.py
> +        dnn_input = combined_dnn_input(sparse_embedding_list, [])  # (batch_size, feat_num * embedding_size)
为啥dense feat没了？

2021-03-21 03:24 UTC, shenweichen commented on deepctr_torch/models/difm.py
> +        dnn_input = combined_dnn_input(sparse_embedding_list, [])
dense feat的问题 和ifm一样的

2021-03-21 03:27 UTC, shenweichen commented on deepctr_torch/models/basemodel.py
> +            batch_size *= len(self.gpus)  # input `batch_size` is batch_size per gpu
多gpu下，原先的逻辑会将batch_size除以gpu个数送入每个gpu是吗？所以这里要补偿一下

2021-03-21 03:47 UTC, shenweichen requested changes
先看下评论～

2021-03-21 04:12 UTC, zanshuxun commented on deepctr_torch/layers/interaction.py
> +            nn.ParameterList
笔误。。。这行后面删掉

测试用例可以覆盖到这个分支，有parameterization == 'vector'的测试用例：
https://github.com/shenweichen/DeepCTR-Torch/blob/d18ea26c09ccc16541dd7985d6ba0a8895bc288d/tests/models/DCN_test.py#L10

2021-03-21 04:20 UTC, zanshuxun commented on deepctr_torch/layers/interaction.py
> +            self.kernels = nn.Parameter(torch.Tensor(self.layer_num, in_features, 1))
[使用ParameterList的话多GPU会报错，原因是pytorch有bug（[issues 36035](https://github.com/pytorch/pytorch/issues/36035)），ParameterList无法被复制至其他GPU。

所以使用Parameter封装一个3维tensor来代替ParameterList。

2021-03-21 04:20 UTC, zanshuxun commented on deepctr_torch/layers/interaction.py
> +        for i in range(self.kernels.shape[0]):
看着更简洁，参考了AFM中的写法：
https://github.com/shenweichen/DeepCTR-Torch/blob/6830fb46b49a328fd0a0671160bf406d4f8248e5/deepctr_torch/layers/interaction.py#L279-L293

2021-03-21 04:23 UTC, zanshuxun commented on deepctr_torch/models/din.py
> +                "dcn, dcnmix and din are not supported with multi gpus now!")
dcn和dcnmix中的参数改为nn.Parameter后已经可以了   这里忘记改了

din无法支持的原因：在模型__init__外使用.to(device)定义tensor，导致该tensor未复制至其他gpu

2021-03-21 04:30 UTC, zanshuxun commented on deepctr_torch/models/ifm.py
> +        dnn_input = combined_dnn_input(sparse_embedding_list, [])  # (batch_size, feat_num * embedding_size)
IFM和DIFM论文中的输入特征均为sparse feature，使用特征的embedding学习输入感知因子（即权重），然后作用于这些embedding。

目前库中也有一些模型无法处理dense feat，例如AFM。

2021-03-21 04:30 UTC, zanshuxun commented on deepctr_torch/models/difm.py
> +        dnn_input = combined_dnn_input(sparse_embedding_list, [])
同上

2021-03-21 04:35 UTC, zanshuxun commented on deepctr_torch/models/basemodel.py
> +            batch_size *= len(self.gpus)  # input `batch_size` is batch_size per gpu
是这样的

2021-04-04 05:12 UTC, shenweichen approved these changes
good

2021-04-04 05:27 UTC, merged