fix #106: model save issue
shenweichen/DeepCTR-Torch pull request #195
Opened 2021-07-12 13:19 UTC by gaohongkui

解决了 #106  无法保存模型的bug。

原因是lambda表达式无法被pickled。

在`basemodel.py`中的`accuracy`使用了lambda表达式
https://github.com/shenweichen/DeepCTR-Torch/blob/b4d8181e86c2165722fa9331bc16185832596232/deepctr_torch/models/basemodel.py#L492-L494

https://github.com/shenweichen/DeepCTR-Torch/issues/106#issuecomment-862417549 给出了复现方法

2021-07-12 14:24 UTC, shenweichen commented on deepctr_torch/models/basemodel.py
> +
多余的空行删下

2021-07-12 14:25 UTC, shenweichen requested changes
多余的空行删除下

2021-07-13 04:38 UTC, merged

2021-07-13 04:49 UTC, shenweichen commented
不要自己merge代码，重新提交一下pull request吧

2021-07-13 04:59 UTC, gaohongkui commented
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 中午12:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [shenweichen/DeepCTR-Torch] fix #106: model save issue (#195)





 
不要自己merge代码，重新提交一下pull request吧
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.